#!/usr/bin/env python3
"""Vendor a subset of Catppuccin Icons into ui/icons.svg as one inline sprite.

Run by hand when the icon set needs refreshing:

    python3 scripts/vendor-icons.py

The output is committed, so a build and an install never reach the network for
this. Bump SHA to move to a newer upstream, add names to ICONS to cover more
file types, then re-run and commit the result.

Why a sprite rather than one file per icon: the upstream css-variables build
colours itself from custom properties, and an <img> is a separate document that
cannot see the page's variables. The sprite is injected into the document at
boot (see loadIcons in ui/app.js) so `<use>` resolves in the same document and
the palette in ui/style.css applies.
"""
import os
import re
import sys
import urllib.request

SHA = "b6915da9f6889b683a110aa747de96c2820a537d"
BASE = f"https://raw.githubusercontent.com/catppuccin/vscode-icons/{SHA}/icons/css-variables"

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, os.pardir, "ui", "icons.svg")

ICONS = [
    # defaults and the three kinds the file list distinguishes
    "_file", "_folder", "_folder_open", "symlink", "text", "binary",
    # languages
    "rust", "python", "javascript", "typescript", "go", "c", "c-header",
    "cpp", "cpp-header", "java", "ruby", "php", "nix", "vim", "bash",
    "powershell",
    # data and markup
    "json", "yaml", "toml", "markdown", "html", "css", "xml", "csv",
    "database", "log",
    # things that turn up in a project root
    "config", "env", "lock", "git", "docker", "makefile", "cmake",
    "license", "readme", "changelog", "contributing", "todo",
    # media and binaries
    "pdf", "zip", "image", "video", "audio", "font", "key", "certificate",
    "exe",
]


def fetch(name):
    req = urllib.request.Request(
        f"{BASE}/{name}.svg", headers={"User-Agent": "linuxwebdesk-vendor"}
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode()


def inner(svg):
    """The drawing, without the outer <svg> wrapper."""
    m = re.search(r"<svg\b[^>]*>(.*)</svg>\s*$", svg, re.S)
    if not m:
        raise ValueError("unexpected svg shape")
    return re.sub(r"\n\s*", " ", m.group(1).strip())


def symbol_id(name):
    """_folder_open -> i-folder-open, c-header -> i-c-header."""
    return "i-" + name.lstrip("_").replace("_", "-")


def main():
    parts, seen = [], set()
    for name in ICONS:
        try:
            raw = fetch(name)
        except Exception as e:
            print(f"  FAILED {name}: {e}", file=sys.stderr)
            return 1
        vb = re.search(r'viewBox="([^"]+)"', raw)
        body = inner(raw)
        seen.update(re.findall(r"var\((--[a-z0-9-]+)\)", body))
        parts.append(
            f'<symbol id="{symbol_id(name)}" '
            f'viewBox="{vb.group(1) if vb else "0 0 16 16"}">{body}</symbol>'
        )
        print(f"  {name:<14} -> #{symbol_id(name)}")

    doc = (
        "<!-- Catppuccin Icons -- MIT, see ui/icons.LICENSE.\n"
        "     https://github.com/catppuccin/vscode-icons\n"
        f"     Vendored subset of icons/css-variables at {SHA}.\n"
        "     Generated by scripts/vendor-icons.py; do not edit by hand.\n"
        "     Injected into the document at boot so the --vscode-ctp-* variables\n"
        "     defined in ui/style.css apply -- an <img> could not see them. -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">\n'
        + "\n".join(parts)
        + "\n</svg>\n"
    )
    with open(OUT, "w") as f:
        f.write(doc)

    print(f"\nwrote ui/icons.svg -- {len(parts)} symbols, {len(doc)} bytes")
    print("variables the icons expect ui/style.css to define:")
    for v in sorted(seen):
        print("   ", v)
    return 0


if __name__ == "__main__":
    sys.exit(main())
